# Generated by Django 4.1.5 on 2023-01-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_shippingadress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingadress',
            name='adress_2',
            field=models.CharField(blank=True, help_text='Bâtiment, étage, lieu-dit,...', max_length=1024),
        ),
        migrations.AlterField(
            model_name='shippingadress',
            name='adress_1',
            field=models.CharField(help_text='Adresse de voirie et numéro de rue.', max_length=1024),
        ),
    ]
