# Generated by Django 4.1.5 on 2023-01-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shippingadress_adress_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopper',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=90),
        ),
    ]
