# Generated by Django 4.1.5 on 2023-01-09 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_shopper_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingadress',
            old_name='adress_1',
            new_name='address_1',
        ),
        migrations.RenameField(
            model_name='shippingadress',
            old_name='adress_2',
            new_name='address_2',
        ),
    ]
